version: "3.8"

services:
  test:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/automation

    command: /bin/sh -c "ls -ls && pytest -m healthcheck --alluredir=allure-results"


###    Need to add env variables ###
#    environment:
#      - DB_USER=${DB_USER}