version: "3.8"

services:
  test:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/automation
    working_dir: /automation

    command: /bin/sh -c "ls -ls && pytest -m healthcheck --alluredir=allure-results"

