version: "3.8"

services:
  test:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/automation

    command: /bib/sh -c "pytest -m healthcheck --alluredir=allure-results"

