name: Running framework healthcheck

on: push

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/pages

      - name: Run docker-compose
        ### Need to add secrets ###
#        env:
#          DB_USER: ${{ secrets.DB_USER }}
        run: |
          docker-compose up --exit-code-from test || true

      - name: Copy results
        run: |
          sudo mkdir -p allure-results/history  # Создает директорию для истории Allure
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          docker-compose run test /bin/sh -c "allure generate allure-results --clean -o allure-reports"

      - name: Copy to gh-pages/history
        run: |
          sudo cp -R allure-reports/history/* ./.github/gh-pages/history/

      - name: Deploy Allure report
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          folder: allure-reports
          branch: gh-pages


